spring:
    application:
      name: nms-configuration
    datasource:
      url: 'jdbc:postgresql://localhost:5432/postgres'
      username: postgres
      password: pg
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    threads:
      virtual:
        enabled: true
    data:
      redis:
        host: localhost
        port: 6379
server:
  port: 8081
  error:
    path: /error
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
