spring:
    application:
      name: nms-configuration
    datasource:
      url: 'jdbc:postgresql://localhost:5432/postgres'
      username: postgres
      password: pg
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    redis:
      host: localhost
      port: '6379'
    threads:
      virtual:
        enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
