spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: nms-configuration
          uri: lb://nms-configuration
          predicates:
            - Path=/c/**
        - id: nms-monitoring
          uri: lb://nms-monitoring
          predicates:
            - Path=/m/**
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



