spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: nms-configuration
#          uri: lb://nms-configuration
#          predicates:
#            - Path=/c/**
#        - id: nms-monitoring
#          uri: lb://nms-monitoring
#          predicates:
#            - Path=/m/**
server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



